# Generated by Django 4.2.1 on 2023-05-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='Link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
